# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b6b25f793d84ff46bbee7b422a250b83ba7bb61d2c934b5110584c3421eb37d1483cea43ffbb967c479a71a8be7841a7fcbf2cc1530b932c2bfc532060ae1977

test:
  secret_key_base: f1851259a76c8787b625f83c5f85ba7930ca0ec8e0d1607efff8e3d70c6af01b78fd5bf76b5cd92325403e7392368540d8ed4de86d2de0b67692e51d9de0d5dd

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
